# Generated by Django 3.2.4 on 2021-06-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_street', models.CharField(max_length=100)),
                ('branch_poc', models.CharField(max_length=100)),
                ('branch_pin', models.CharField(max_length=100)),
                ('poc_contact_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=40, unique=True)),
                ('city_shortname', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financial_Year',
            fields=[
                ('year_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('finacial_year', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GST',
            fields=[
                ('gst_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('gst_percent', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('party_name', models.CharField(max_length=100, unique=True)),
                ('party_street', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=40)),
                ('party_email', models.CharField(max_length=40, unique=True)),
                ('party_GST', models.CharField(max_length=40, unique=True)),
                ('party_category', models.CharField(max_length=100)),
                ('party_type', models.CharField(max_length=100)),
                ('party_city', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='party', to='billingapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Mode',
            fields=[
                ('pay_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100)),
                ('HSN_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('invoice_no', models.CharField(max_length=40)),
                ('invoice_date', models.DateField()),
                ('purchase_type', models.CharField(max_length=40)),
                ('remarks', models.CharField(max_length=40)),
                ('purchase_taxableamnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_IGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_CGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_SGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_subtotal', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_Discount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_GTotal', models.DecimalField(decimal_places=3, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=40, unique=True)),
                ('state_code', models.CharField(max_length=40, unique=True)),
                ('state_shortname', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('unit_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('unit_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('unit_shortname', models.CharField(max_length=40, unique=True)),
                ('unit_longname', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_designation', models.CharField(max_length=100)),
                ('user_location', models.CharField(max_length=100)),
                ('user_emnail', models.CharField(max_length=100, unique=True)),
                ('user_contact_no', models.CharField(max_length=100)),
                ('user_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='billingapp.branch')),
            ],
        ),
        migrations.CreateModel(
            name='UOM_Conversion',
            fields=[
                ('conversion_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('operations', models.CharField(max_length=40)),
                ('conversion_value', models.IntegerField()),
                ('fromunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversion_fromunit', to='billingapp.uom')),
                ('tounit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversion_tounit', to='billingapp.uom')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('stock_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('stock_UOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='billingapp.uom')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='billingapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Items_Bridge',
            fields=[
                ('purchasedetails_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('item_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_disc', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_taxable', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_SGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_amnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchade_items_bridge', to='billingapp.product')),
                ('purchase_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchade_items_bridge', to='billingapp.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_Item',
            field=models.ManyToManyField(related_name='purchase', through='billingapp.Purchase_Items_Bridge', to='billingapp.Product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_Paymode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='billingapp.payment_mode'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_state',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='billingapp.state'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='billingapp.party'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='billingapp.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='billingapp.gst'),
        ),
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('payment_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=40, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('card_no', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('card_expiry_date', models.DateField(blank=True, null=True)),
                ('cvc_code', models.IntegerField(blank=True, max_length=10, null=True)),
                ('referrence_no', models.CharField(blank=True, max_length=40, null=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='billingapp.payment_mode')),
                ('purchase_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='billingapp.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='party_state',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='party', to='billingapp.state'),
        ),
        migrations.CreateModel(
            name='GST_wise',
            fields=[
                ('gst_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('gst_rate', models.IntegerField()),
                ('taxable_amnt', models.DecimalField(decimal_places=3, max_digits=15)),
                ('CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('SGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('purchase_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_wise', to='billingapp.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=40, unique=True)),
                ('company_street', models.CharField(max_length=100)),
                ('company_pin', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100, unique=True)),
                ('company_url', models.CharField(max_length=100, unique=True)),
                ('contact_no', models.CharField(max_length=100)),
                ('company_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='billingapp.city')),
                ('company_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='billingapp.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='billingapp.state'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='billingapp.city'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='billingapp.state'),
        ),
    ]
