# Generated by Django 3.2.4 on 2021-07-10 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cvc_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='billingapp.uom'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_shortname',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
