# Generated by Django 3.2.4 on 2021-07-15 02:58

import billingapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0003_auto_20210713_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_GST',
            fields=[
                ('category_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=40, unique=True)),
                ('gst_percent', models.CharField(max_length=40, unique=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='HSN_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gst',
        ),
        migrations.AddField(
            model_name='gst_wise',
            name='purchase_receiptno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='poc_contact_no',
            field=models.CharField(max_length=100, validators=[billingapp.models.validate_mobileno]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(max_length=100, unique=True, validators=[billingapp.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_no',
            field=models.CharField(max_length=100, validators=[billingapp.models.validate_mobileno]),
        ),
        migrations.AlterField(
            model_name='party',
            name='contact_no',
            field=models.CharField(max_length=40, validators=[billingapp.models.validate_mobileno]),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_email',
            field=models.CharField(max_length=40, unique=True, validators=[billingapp.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_contact_no',
            field=models.CharField(max_length=100, validators=[billingapp.models.validate_mobileno]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=100, unique=True, validators=[billingapp.models.validate_email]),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.CheckConstraint(check=models.Q(('state_code__lte', 99)), name='state_code_constarint'),
        ),
        migrations.DeleteModel(
            name='GST',
        ),
        migrations.AddField(
            model_name='category_gst',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_gst', to='billingapp.financial_year'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='billingapp.category_gst'),
        ),
    ]
