# Generated by Django 3.2.4 on 2021-08-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0005_auto_20210806_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_taxableamnt',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Taxbl Amt'),
        ),
    ]
