# Generated by Django 3.2.4 on 2021-08-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0006_alter_purchase_purchase_taxableamnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_Item',
            field=models.ManyToManyField(blank=True, related_name='purchase', through='billingapp.Purchase_Items_Bridge', to='billingapp.Product'),
        ),
    ]
