# Generated by Django 3.2.4 on 2021-08-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0007_alter_purchase_purchase_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_Item',
        ),
    ]
