# Generated by Django 3.2.4 on 2021-10-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0008_remove_purchase_purchase_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Returns',
            fields=[
                ('purchasereturns_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('invoice_date', models.DateField()),
                ('purchase_type', models.CharField(max_length=40)),
                ('remarks', models.CharField(max_length=40)),
                ('purchase_taxableamnt', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Taxbl Amt')),
                ('purchase_IGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_CGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_SGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_subtotal', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_Discount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_GTotal', models.DecimalField(decimal_places=3, max_digits=18)),
                ('purchase_Paymode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='billingapp.payment_mode')),
                ('purchase_state', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='billingapp.state')),
                ('return_invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='billingapp.purchase')),
                ('supplier', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='billingapp.party')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_Bin_Stock',
            fields=[
                ('warehouse_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Warehouse', models.CharField(blank=True, max_length=20, null=True)),
                ('Bin', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_bin_stock', to='billingapp.product')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_bin_stock', to='billingapp.uom')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Returns_GST_wise',
            fields=[
                ('purchase_returns_gst_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('gst_rate', models.IntegerField()),
                ('purchase_receiptno', models.CharField(blank=True, max_length=15, null=True)),
                ('taxable_amnt', models.DecimalField(decimal_places=3, max_digits=15)),
                ('CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('SGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('purchase_returns_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns_gst_wise', to='billingapp.purchase_returns')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Items_Returns_Bridge',
            fields=[
                ('purchase_returnsdetails_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('item_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('base_item_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_hsncode', models.CharField(blank=True, max_length=20, null=True)),
                ('base_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('item_rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_disc', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_taxable', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_SGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_amnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items_returns_bridge', to='billingapp.product')),
                ('purchase_returns_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items_returns_bridge', to='billingapp.purchase_returns')),
                ('uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items_returns_bridge', to='billingapp.uom')),
            ],
        ),
    ]
