# Generated by Django 3.2.4 on 2021-11-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billingapp', '0009_purchase_items_returns_bridge_purchase_returns_purchase_returns_gst_wise_warehouse_bin_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('sales_invoiceno', models.CharField(max_length=40)),
                ('invoice_date', models.DateField()),
                ('sales_type', models.CharField(max_length=40)),
                ('sales_remarks', models.CharField(max_length=40)),
                ('sales_taxableamount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_IGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_CGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_SGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_subtotal', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_Discount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_GTotal', models.DecimalField(decimal_places=3, max_digits=18)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.party')),
                ('sales_Paymode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='billingapp.payment_mode')),
                ('sales_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Items_Bridge',
            fields=[
                ('salesdetails_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('salesitem_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_hsncode', models.CharField(blank=True, max_length=20, null=True)),
                ('salesitem_rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_disc', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_taxable', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_SGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_amnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items_bridge', to='billingapp.product')),
                ('sales_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items_bridge', to='salesapp.sales')),
                ('sales_uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_items_bridge', to='billingapp.uom')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_GST_Wise',
            fields=[
                ('salesgst_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('salesgst_rate', models.IntegerField()),
                ('sales_receiptno', models.CharField(blank=True, max_length=15, null=True)),
                ('salest_axable_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_CGST_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_SGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_SGST_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_IGST_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_gst_wise', to='salesapp.sales')),
            ],
        ),
    ]
