# Generated by Django 3.2.4 on 2021-11-24 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0010_auto_20211124_0320'),
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_gst_wise',
            old_name='salest_axable_amount',
            new_name='salest_taxable_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_remarks',
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_credit',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sales_items_bridge',
            name='sales_item_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sales_items_bridge',
            name='salesitem_CGSTamnt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sales_items_bridge',
            name='salesitem_IGSTamnt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sales_items_bridge',
            name='salesitem_SGSTamnt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='billingapp.party'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_invoiceno',
            field=models.CharField(max_length=40, verbose_name='Billing No'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='billingapp.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_type',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=40, null=True),
        ),
    ]
