# Generated by Django 3.2.4 on 2021-12-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_auto_20211124_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_gst_wise',
            old_name='salest_taxable_amount',
            new_name='sales_taxable_amount',
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_type',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=40, null=True, verbose_name='Sales Type'),
        ),
        migrations.AlterField(
            model_name='sales_items_bridge',
            name='salesitem_disc',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
