# Generated by Django 3.2.4 on 2022-01-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0010_auto_20211124_0320'),
        ('salesapp', '0003_auto_20211227_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Returns_GST_Wise',
            fields=[
                ('sales_returns_gst_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('salesgst_rate', models.IntegerField()),
                ('sales_receiptno', models.CharField(blank=True, max_length=15, null=True)),
                ('sales_taxable_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_CGST_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_SGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_SGST_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_IGST_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sales_returns_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns_gst_wise', to='salesapp.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Returns',
            fields=[
                ('salesreturns_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('invoice_date', models.DateField()),
                ('sales_type', models.CharField(max_length=40)),
                ('sales_credit', models.CharField(blank=True, max_length=40, null=True)),
                ('sales_taxableamnt', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Taxbl Amt')),
                ('sales_IGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_CGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_SGSTAmnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_subtotal', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_Discount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_GTotal', models.DecimalField(decimal_places=3, max_digits=18)),
                ('customer', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='billingapp.party')),
                ('return_salesinvoiceno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='salesapp.sales')),
                ('sales_Paymode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='billingapp.payment_mode')),
                ('sales_state', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='billingapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Items_Return_Bridge',
            fields=[
                ('salesreturns_details_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('sales_item_code', models.CharField(blank=True, max_length=20, null=True)),
                ('salesitem_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('base_salesitem_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_hsncode', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_base_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('salesitem_rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_disc', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('salesitem_taxable', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_CGSTamnt', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('salesitem_SGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_SGSTamnt', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('salesitem_IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('salesitem_IGSTamnt', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('salesitem_amnt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns_items_bridge', to='billingapp.product')),
                ('sales_returns_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns_items_bridge', to='salesapp.sales')),
                ('sales_uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns_items_bridge', to='billingapp.uom')),
            ],
        ),
    ]
